server:
  port: 8080
spring:
  application:
    name: lunamm metadata manager api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lunamm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    enabled: true
    cache: true
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/

mybatis:
  # 配置指向实体类包路径。
  typeAliasesPackage: org.luna.learn.metamanager.mapper
  # 配置为 classpath 路径下 mapper 包下，* 代表会扫描所有 xml 文件。
  mapperLocations: classpath\:mapper/*.xml